### PR TITLE
file_qe: minor fix

### PR DESCRIPTION
**Pull request by ovhpa**
Just a minor fix in file_qe.c
-> strrstr catch a wrong line with "total energy" in the output, which cause some trouble in property/property_list. I just removed the line manually (maybe not an optimal solution).

On a side note, I commit the first implementation for plots on a new branch on my fork.
I'm doing some cosmetic changes on gl_graph.c and finishing DOS/BAND plots.
I won't open a pull request until I fix the few bugs remaining, but it started to look not so bad I think.

### CODE REVIEW

**Comment by arohl** [comment]
Can you send me a file that has both the line you want to catch as well as the one you don't? Manually deleting is definitely suboptimal!

**Comment by ovhpa** [comment]
The file hippuric.qeout in models directory has both line:
`grep "total energy" models/hippuric.qeout`

Until I did some use of properties it doesn't really matter so much, but anyway it's better not to catch a bad line I think.

**Comment by arohl** [comment]
Sorry - I didn't understand; your changes now handle the "The total energy is the sum of the following terms" line correctly (by ignoring)

**Comment by ovhpa** [comment]
Yes, sorry I didn’t explain properly: as you said the incorrect line is now ignored. 
Also  it’s not optimal because a test is done for a bad line each time a good one matches.

**Pull request merged**
