### PR TITLE
Uspex output

### PR DESCRIPTION
**Pull request by ovhpa**
Dear Prof. Rohl,

How about this first implementation for reading USPEX outputs?

Its use is quite straightforward: at first all structures are loaded (in this example about 10000 structures) and related graphs are created:
us_00

Then one can navigate through structures of interest simply by selecting a corresponding energy data square on the graph, which will load the corresponding structure model on the previous screen (actually it just jumps to the corresponding structure representation that was previously loaded):
us_01
or equivalently the "best structure" graph, which is calculated using either the lowest energies of fitness figure.

When composition varies, an elementary graph of atomic composition x [0,1] (with x the atomic ratio, relative to the total atom number for that structure) is automatically plotted:
us_02
(it is also navigable)

Finally for VCNEB calculation, a simple energy vs image (also selectable) is drawn:
us_03

For now, USPEX, META, and VCNEB calculation "types" are supported, but I'm planning to add additional analysis (such as hardness, volume, ect.) at a later date.

Sincerely,

PS: I have also hide some compiler warning mostly about variables "set but not used" under a precompiler define (UNUSED_BUT_SET) for presentation purpose (which is why so many files are modified). If it causes some problem, I can revert that change later.

### CODE REVIEW

**Comment by arohl** [comment]
This looks terrific! I haven't used USPEX myself but we do have a project that will need it, so this integration will make it much easier. 

Would you like me to give you access to make commits to the main branch yourself or do you prefer doing it this way?

  Andrew

PS Can you convert the above to become part of the help system?

**Comment by ovhpa** [comment]
Thank you very much for your comment.

Integration of uspex with gdis is part of a visiting project I have with France that will kick off in September (involving uspex, vasp, and maybe gulp calculations).
At that time I will surely have to make many commits to gdis, so doing so directly on the main branch would certainly help :)
And you are right, the help system should be updated, since loading an uspex OUTPUT.txt file is rather different from the usual. I’ll modify it later this week.

Sincerely,

**Comment by arohl** [comment]
Hopefully you can now commit

  Andrew

On 6 Jun 2018, at 9:31 am, Okadome Valencia <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you very much for your comment.

Integration of uspex with gdis is part of a visiting project I have with France that will kick off in September (involving uspex, vasp, and maybe gulp calculations).
At that time I will surely have to make many commits to gdis, so doing so directly on the main branch would certainly help :)
And you are right, the help system should be updated, since loading an uspex OUTPUT.txt file is rather different from the usual. I’ll modify it later this week.

Sincerely,

**Comment by ovhpa** [comment]
I can. Thank you!

**Pull request merged**
